name       : canon-ufriilt-common
version    : '5.30'
release    : 5
source     :
    - https://gdlp01.c-wss.com/gds/0/0100009240/16/linux-UFRII-drv-v530-uken-10.tar.gz : ea82a9900d7140024a494cd383e07d86eb73cafb47cdb8be24d3f1b24124a90e
license    :
    - GPL-2.0
    - MIT
component  : desktop.library
summary    : Canon UFRII LT Printer Driver for Linux
description: |
    Canon UFR II/UFRII LT Printer Driver for Linux
builddeps  :
    - pkgconfig(libglade-2.0)
    - cups-devel
setup      : |
    cd Sources
    tar xvf cnrdrvcups-lb-${version}-1.tar.gz
    pushd cnrdrvcups-common-${version}
    for dir in cngplp buftool backend; do
        pushd $dir
        %autogen
        popd
    done
build      : |
    cd Sources/cnrdrvcups-common-${version}
    for dir in cngplp buftool backend; do
        pushd $dir
        %make -j1
        popd
    done
install    : |
    cd Sources/cnrdrvcups-common-${version}
    for dir in cngplp buftool backend; do
        pushd $dir
        %make_install -j1
        popd
    done
