name       : canon-ufriilt-common
version    : '3.80'
release    : 3
source     :
    - http://gdlp01.c-wss.com/gds/8/0100002708/17/linux-UFRII-drv-v340-uken.tar.gz : fb3701f564f987126a9a3d03a163951f3182d6f7d626530a6767cb1f996fa203
license    :
    - GPL-2.0
    - MIT
component  : desktop.library
summary    : Canon UFRII LT Printer Driver for Linux
description: |
    Canon UFR II/UFRII LT Printer Driver for Linux
builddeps  :
    - pkgconfig(libglade-2.0)
    - cups-devel
setup      : |
    cd Sources
    tar xvf cndrvcups-common-${version}-1.tar.gz
    pushd cndrvcups-common-${version}
    for dir in cngplp buftool backend; do
        pushd $dir
        %autogen
        popd
    done
build      : |
    cd Sources/cndrvcups-common-${version}
    for dir in cngplp buftool backend; do
        pushd $dir
        %make -j1
        popd
    done
install    : |
    cd Sources/cndrvcups-common-${version}
    for dir in cngplp buftool backend; do
        pushd $dir
        %make_install -j1
        popd
    done
