name       : canon-ufriilt-common
version    : 3.71
release    : 2
source     :
    - http://gdlp01.c-wss.com/gds/8/0100002708/16/linux-UFRII-drv-v331-uken.tar.gz : c1211cbe27034847284541fcc613b86ccfe99418a6a2cbb4589b99ffe1af4645
license    :
    - GPL-2.0
    - MIT
component  : desktop.library
summary    : Canon UFRII LT Printer Driver for Linux
description: |
    Canon UFR II/UFRII LT Printer Driver for Linux
builddeps  :
    - pkgconfig(libglade-2.0)
    - cups-devel
setup      : |
    cd Sources
    tar xvf cndrvcups-common-3.71-1.tar.gz
    pushd cndrvcups-common-3.71
    for dir in cngplp buftool backend; do
        pushd $dir
        %autogen
        popd
    done
build      : |
    cd Sources/cndrvcups-common-3.71
    for dir in cngplp buftool backend; do
        pushd $dir
        %make -j1
        popd
    done
install    : |
    cd Sources/cndrvcups-common-3.71
    for dir in cngplp buftool backend; do
        pushd $dir
        %make_install -j1
        popd
    done
